packages:
  - apps/*
  - packages/*
  - tools/*
catalog:
  '@eslint/js': ^9.25.1
  '@hono/node-server': ^1.14.1
  '@hono/trpc-server': ^0.3.4
  '@radix-ui/react-avatar': ^1.1.7
  '@radix-ui/react-dialog': ^1.1.11
  '@radix-ui/react-dropdown-menu': ^2.1.12
  '@radix-ui/react-icons': ^1.3.2
  '@radix-ui/react-label': ^2.1.4
  '@radix-ui/react-slot': ^1.2.0
  '@radix-ui/react-toast': ^1.2.11
  '@radix-ui/react-tooltip': ^1.2.4
  '@tailwindcss/vite': ^4.1.5
  '@tanstack/react-form': ^1.9.0
  '@tanstack/react-query': ^5.74.11
  '@tanstack/react-router': ^1.119.0
  '@tanstack/router-devtools': ^1.119.1
  '@tanstack/router-plugin': ^1.119.0
  '@trpc/client': ^11.1.2
  '@trpc/server': ^11.1.2
  '@trpc/tanstack-react-query': ^11.1.2
  '@types/eslint-config-prettier': ^6.11.3
  '@types/node': ^22.15.3
  '@types/pg': ^8.11.14
  '@types/react': ^19.1.2
  '@types/react-dom': ^19.1.3
  '@vitejs/plugin-react-swc': ^3.9.0
  better-auth: ^1.2.7
  class-variance-authority: ^0.7.1
  dotenv-cli: ^8.0.0
  drizzle-kit: ^0.31.0
  drizzle-orm: ^0.43.1
  drizzle-valibot: ^0.4.1
  eslint: ^9.25.1
  eslint-config-prettier: ^10.1.2
  eslint-config-turbo: ^2.5.2
  eslint-plugin-import: ^2.31.0
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-turbo: ^2.5.2
  globals: ^16.0.0
  hono: ^4.7.8
  next-themes: ^0.4.6
  pg: ^8.15.6
  prettier: ^3.5.3
  radix-ui: ^1.3.4
  react: ^19.1.0
  react-dom: ^19.1.0
  shx: ^0.4.0
  sonner: ^2.0.3
  superjson: ^2.2.2
  tailwind-merge: ^3.2.0
  tailwindcss: ^4.1.5
  tailwindcss-animate: ^1.0.7
  tsup: ^8.4.0
  tsx: ^4.19.4
  turbo: ^2.5.2
  typescript: ^5.8.3
  typescript-eslint: ^8.31.1
  url-join: ^5.0.0
  valibot: ^1.0.0
  vite: ^6.3.4
